from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping, Protocol

from .models import WorkspaceRequest, WorkspaceStatus, WorkspaceValidation


class FileSystemAdapter(Protocol):
    def resolve(self, path: str | Path) -> Path: ...

    def exists(self, path: Path) -> bool: ...

    def is_file(self, path: Path) -> bool: ...

    def is_directory(self, path: Path) -> bool: ...

    def make_directory(self, path: Path) -> None: ...

    def read_text(self, path: Path) -> str: ...

    def write_text(self, path: Path, content: str) -> None: ...

    def append_text(self, path: Path, content: str) -> None: ...


class WorkspaceDriverPort(Protocol):
    def defaults(self) -> Mapping[str, str | None]: ...

    def validate(self, request: WorkspaceRequest) -> WorkspaceValidation: ...

    def create(self, request: WorkspaceRequest) -> WorkspaceStatus: ...

    def status(self, run_id: str) -> WorkspaceStatus: ...

    def save_dashboard_state(self, run_id: str, payload: Mapping[str, Any]) -> None: ...

    def load_dashboard_state(self, run_id: str) -> Mapping[str, Any] | None: ...
